"""Stage 3 — Memo rendering.

Turns an Analysis into a one-page Markdown memo a partner can read in 60 seconds:
the call is at the very top, then the score breakdown, then rationale, then the
"what would change my mind" list, then every source. No claim appears without a
traceable source.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone

from .models import Analysis

_CALL_EMOJI = {"Take a meeting": "🟢", "Watch": "🟡", "Pass": "🔴"}


def _slug(name: str) -> str:
    """Filesystem-safe filename stem from a startup name."""
    s = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return s or "candidate"


def render_memo(a: Analysis) -> str:
    c = a.candidate
    s = a.score
    emoji = _CALL_EMOJI.get(a.call, "")

    lines: list[str] = []
    lines.append(f"# {c.name}")
    lines.append("")
    lines.append(f"## {emoji} Call: **{a.call}**")
    lines.append("")
    lines.append(f"*{a.call_reason}*")
    lines.append("")
    lines.append(f"> {c.one_liner or '_no one-liner found_'}")
    lines.append("")
    lines.append(f"- **Website:** {c.website}")
    lines.append(f"- **Sourced from:** {c.source.replace('_', ' ').title()}")
    if c.founders_signal:
        lines.append(f"- **Team signal:** {c.founders_signal}")
    lines.append("")

    # Score table
    lines.append(f"## Score: {s.total} / 100")
    lines.append("")
    lines.append("| Component | Score | Why |")
    lines.append("|---|---:|---|")
    lines.append(f"| Technical depth | {s.technical_depth} / 30 | {s.notes['technical_depth']} |")
    lines.append(f"| Open-source wedge | {s.open_source_wedge} / 25 | {s.notes['open_source_wedge']} |")
    lines.append(f"| Organic traction | {s.organic_traction} / 25 | {s.notes['organic_traction']} |")
    lines.append(f"| Market / why-now | {s.market_timing} / 20 | {s.notes['market_timing']} |")
    lines.append(f"| **Total** | **{s.total} / 100** | |")
    lines.append("")

    # Narrative
    for heading, body in [
        ("Team", a.team), ("Product", a.product),
        ("Market", a.market), ("Risks / open questions", a.risks),
    ]:
        lines.append(f"## {heading}")
        lines.append("")
        lines.append(body)
        lines.append("")

    # What would change my mind
    lines.append("## What would change the call")
    lines.append("")
    for item in a.change_my_mind:
        lines.append(f"- {item}")
    lines.append("")

    # Sources
    lines.append("## Sources")
    lines.append("")
    lines.append("Every claim above traces back to one of these:")
    lines.append("")
    for src in a.sources:
        lines.append(f"- {src['claim']}: {src['source']}")
    lines.append("")

    # Provenance footer
    lines.append("---")
    lines.append(f"*Narrative generated by: `{a.generated_by}`. "
                 f"Score computed deterministically from public signals. "
                 f"Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}.*")
    lines.append("")
    return "\n".join(lines)


def memo_filename(a: Analysis) -> str:
    return f"{_slug(a.candidate.name)}.md"
